### ISSUE TITLE
Interesting links

### ISSUE THREAD

**Issue by devinrhode2** [thormagnusson/ixilang#7]
Don't mean to pollute github, but wanted to share some interesting links here:
1. Thor's paper on ixiQuarks extension: http://www.ixi-software.net/thor/ixiQuarksICMC.pdf
2. This WulfCode project which uses instruments from Ableton Live in case you don't know how to make SC instruments (Could be nice for certain beginners) https://www.youtube.com/watch?v=F2--JzAvPsg

**Comment by thormagnusson** [comment]
Oh, thanks. I hadn't seen WulfCode. Very nice.
